"""Add terms_accepted

Revision ID: 537affa35b6d
Revises: b999acf5643e
Create Date: 2026-01-05 07:52:15.901220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537affa35b6d'
down_revision: Union[str, Sequence[str], None] = 'b999acf5643e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'terms_accepted')
    # ### end Alembic commands ###
